export type GuideCategory = "kien-thuc-giat-say" | "giat-chan-men" | "ve-sinh-giay" | "tay-vet-ban" | "cham-soc-quan-ao";

export type Guide = {
  slug: string;
  title: string;
  category: GuideCategory;
  summary: string;
  firstAction: string;
  serviceSlug: "giat-say-can-tho" | "giat-chan-men-can-tho" | "ve-sinh-giay-can-tho";
  risk?: "high";
};

const laundry = "giat-say-can-tho" as const;
const bedding = "giat-chan-men-can-tho" as const;
const shoes = "ve-sinh-giay-can-tho" as const;

export const guideCategories: Record<GuideCategory, string> = {
  "kien-thuc-giat-say": "Kiến thức giặt sấy",
  "giat-chan-men": "Chăn mền và đồ cồng kềnh",
  "ve-sinh-giay": "Vệ sinh giày",
  "tay-vet-ban": "Tẩy vết bẩn",
  "cham-soc-quan-ao": "Chăm sóc quần áo"
};

export const guides: Guide[] = [
  { slug: "gia-giat-say-can-tho", title: "Giá giặt sấy ở Cần Thơ tính theo kg như thế nào?", category: "kien-thuc-giat-say", summary: "Giá giặt sấy thường được tính theo cân nặng, loại đồ và yêu cầu xử lý. Tại DN House, khách nên gửi số lượng ước tính để được báo giá trước.", firstAction: "Tách quần áo thường, đồ dày, giày và món cần tẩy điểm trước khi hỏi giá.", serviceSlug: laundry },
  { slug: "giat-ui-giao-nhan-tan-noi-can-tho", title: "Giặt ủi giao nhận tận nơi ở Cần Thơ: quy trình và khu vực phục vụ", category: "kien-thuc-giat-say", summary: "Giao nhận thuận tiện khi khách mô tả rõ loại đồ, số lượng và khu vực. DN House hỗ trợ freeship trong bán kính 3km; khu vực khác cần xác nhận trước.", firstAction: "Chụp nhanh đồ đặc biệt và gửi kèm địa chỉ/khu vực qua Zalo trước khi đặt.", serviceSlug: laundry },
  { slug: "tiem-giat-ui-gan-day", title: "Cách chọn tiệm giặt ủi gần đây uy tín, báo giá rõ ràng", category: "kien-thuc-giat-say", summary: "Một tiệm phù hợp cần báo trước loại dịch vụ, giá tham khảo, thời gian dự kiến và giới hạn xử lý với đồ đặc biệt.", firstAction: "Hỏi rõ giá, hình thức giao nhận và thời gian trả đồ trước khi gửi.", serviceSlug: laundry },
  { slug: "giat-say-lay-lien-can-tho", title: "Giặt sấy lấy liền tại Cần Thơ mất bao lâu?", category: "kien-thuc-giat-say", summary: "Thời gian giặt sấy phụ thuộc số lượng, chất liệu, độ dày và lịch nhận đồ. Không nên hứa thời gian cố định trước khi kiểm tra đơn.", firstAction: "Báo trước thời điểm cần nhận đồ và gửi ảnh nếu có món dày hoặc cần xử lý vết bẩn.", serviceSlug: laundry },
  { slug: "giat-say-mua-mua-can-tho", title: "Mùa mưa Cần Thơ nên giặt phơi hay giặt sấy?", category: "kien-thuc-giat-say", summary: "Khi độ ẩm cao, đồ phơi lâu dễ có mùi. Chọn giặt sấy hay phơi tùy chất liệu, nhãn chăm sóc và khả năng làm khô hoàn toàn.", firstAction: "Đừng cất đồ còn ẩm; kiểm tra mùi và độ khô ở cổ áo, cạp quần, mép dày.", serviceSlug: laundry },
  { slug: "giat-do-sinh-vien-can-tho", title: "Dịch vụ giặt đồ cho sinh viên Cần Thơ: cách tiết kiệm theo kg", category: "kien-thuc-giat-say", summary: "Gom đồ giặt theo mẻ hợp lý giúp dễ kiểm soát chi phí. Đồ trắng, đồ dễ ra màu và món cần giặt tay nên được tách riêng.", firstAction: "Kiểm tra túi áo/quần, phân loại đồ trắng và đồ màu trước khi gom mẻ.", serviceSlug: laundry },
  { slug: "giat-do-cong-so-can-tho", title: "Giặt quần áo công sở ở Cần Thơ sao cho ít nhăn, sạch mùi", category: "kien-thuc-giat-say", summary: "Áo sơ mi, quần tây và đồ công sở cần xem nhãn vải, xử lý vết bẩn sớm và làm khô đúng cách để hạn chế nhăn, ám mùi.", firstAction: "Tách áo có chi tiết dễ hỏng và báo trước các vết bẩn thấy rõ.", serviceSlug: laundry },
  { slug: "giat-dong-phuc-can-tho", title: "Giặt đồng phục học sinh và đồng phục công ty tại Cần Thơ", category: "kien-thuc-giat-say", summary: "Đồng phục cần được phân loại theo màu và loại vải để hạn chế lem màu. Đơn số lượng lớn nên thống nhất thời điểm nhận, trả và yêu cầu gấp.", firstAction: "Phân riêng áo trắng, đồ màu đậm và món có logo/in chuyển nhiệt.", serviceSlug: laundry },
  { slug: "giat-do-em-be-can-tho", title: "Giặt quần áo em bé tại Cần Thơ: lưu ý về cặn giặt và mùi hương", category: "kien-thuc-giat-say", summary: "Đồ em bé nên được giặt theo nhãn, xả kỹ và tránh dùng sản phẩm có mùi quá mạnh nếu da bé nhạy cảm.", firstAction: "Tách đồ em bé khỏi đồ người lớn bẩn nặng và báo nếu bé có da nhạy cảm.", serviceSlug: laundry },
  { slug: "giat-do-so-luong-lon-can-tho", title: "Giặt đồ số lượng lớn ở Cần Thơ: cân ký, phân loại và thời gian trả đồ", category: "kien-thuc-giat-say", summary: "Đơn nhiều đồ cần kiểm đếm, phân loại và chốt yêu cầu trước khi giặt. Cách này hạn chế nhầm lẫn và giúp báo giá, thời gian rõ ràng.", firstAction: "Chia đồ theo nhóm và liệt kê món quan trọng trước khi bàn giao.", serviceSlug: laundry },
  { slug: "giat-rem-cua-can-tho", title: "Giặt rèm cửa Cần Thơ: khi nào cần giặt và bao lâu khô?", category: "giat-chan-men", summary: "Rèm dễ bám bụi và cần xem nhãn chất liệu, kiểu may, khoen hoặc móc treo trước khi giặt. Đồ dày cần đủ thời gian làm khô.", firstAction: "Chụp nhãn rèm, kiểu móc và tình trạng vết bẩn trước khi tháo.", serviceSlug: bedding },
  { slug: "giat-topper-can-tho", title: "Giặt topper tại Cần Thơ: xử lý mùi ẩm và vết bẩn đúng cách", category: "giat-chan-men", summary: "Topper dày khó khô và có thể biến dạng nếu xử lý sai. Cần xác định cấu tạo, nhãn chăm sóc và mức độ ẩm/mốc trước khi làm sạch.", firstAction: "Không ngâm topper khi chưa biết vật liệu; gửi ảnh nhãn và tình trạng để kiểm tra trước.", serviceSlug: bedding, risk: "high" },
  { slug: "giat-goi-can-tho", title: "Giặt gối nằm ở Cần Thơ: gối bông, gối sợi và lưu ý khi sấy", category: "giat-chan-men", summary: "Gối có thể vón, mất form hoặc giữ ẩm nếu giặt sấy không phù hợp. Nhãn của gối là thông tin cần xem trước tiên.", firstAction: "Kiểm tra đường may, ruột gối và nhãn hướng dẫn trước khi giặt.", serviceSlug: bedding },
  { slug: "giat-ga-giuong-can-tho", title: "Bao lâu nên giặt ga giường, drap và vỏ gối một lần?", category: "giat-chan-men", summary: "Tần suất giặt phụ thuộc mồ hôi, thú nuôi, mùa mưa và tình trạng da. Quan trọng là giặt, làm khô hoàn toàn và thay khi có mùi hoặc vết bẩn.", firstAction: "Tách ga sáng màu và màu đậm, xử lý vết mới trước khi cho vào máy.", serviceSlug: bedding },
  { slug: "giat-chan-bong-can-tho", title: "Giặt chăn bông tại Cần Thơ sao cho không vón và không ám mùi?", category: "giat-chan-men", summary: "Chăn bông cần được giặt theo nhãn và làm khô kỹ để hạn chế vón ruột, ẩm mùi. Đồ quá dày có thể cần kiểm tra riêng.", firstAction: "Kiểm tra nhãn, đường may và vết rách trước khi giặt; không cất chăn khi còn ẩm.", serviceSlug: bedding },
  { slug: "giat-thu-bong-can-tho", title: "Giặt thú bông tại Cần Thơ: làm sạch mà không biến dạng", category: "giat-chan-men", summary: "Thú bông có thể có phụ kiện, keo dán hoặc ruột dễ vón. Cần kiểm tra nhãn, đường may và thử ở vùng kín trước khi xử lý.", firstAction: "Tháo phụ kiện rời, kiểm tra đường may hở và không vắt xoắn thú bông.", serviceSlug: bedding },
  { slug: "giat-ao-khoac-can-tho", title: "Giặt áo khoác dày và áo khoác có lớp lót đúng cách", category: "giat-chan-men", summary: "Áo khoác dày, áo có lớp lót hoặc lớp chống nước cần tuân theo nhãn chăm sóc. Giặt sai có thể làm vón, phai hoặc hỏng lớp phủ.", firstAction: "Đóng khóa kéo, lộn trái áo và xem kỹ nhãn trước khi giặt.", serviceSlug: laundry },
  { slug: "giat-balo-can-tho", title: "Giặt balo tại Cần Thơ: xử lý mốc, mùi và vết bẩn trong ngăn túi", category: "giat-chan-men", summary: "Balo cần được làm trống ngăn, kiểm tra da, lớp phủ và khóa kéo. Không phải balo nào cũng phù hợp ngâm hoặc giặt máy.", firstAction: "Lấy hết đồ trong ngăn, chụp tình trạng mốc/vết bẩn và xem nhãn nếu còn.", serviceSlug: laundry, risk: "high" },
  { slug: "giat-non-can-tho", title: "Vệ sinh nón kết, nón vải sao cho không mất form", category: "giat-chan-men", summary: "Nón dễ mất form khi ngâm lâu, vắt mạnh hoặc phơi sai. Cần xem phần vành, khung, tem và chất liệu trước khi làm sạch.", firstAction: "Không bẻ vành hoặc vò xoắn nón; dùng khăn sạch thấm nước để thử vùng khuất.", serviceSlug: laundry },
  { slug: "giat-man-chong-muoi", title: "Cách giặt màn, mùng chống muỗi sạch bụi mà không rách lưới", category: "giat-chan-men", summary: "Lưới mùng mỏng, dễ mắc và rách. Nên giũ bụi, giặt nhẹ và kiểm tra rách nhỏ trước khi giặt.", firstAction: "Gỡ móc cẩn thận, buộc gọn phần lưới và tránh giặt chung với khóa kéo hoặc vật sắc.", serviceSlug: bedding },
  { slug: "ve-sinh-giay-trang", title: "Cách vệ sinh giày trắng bị bẩn và hạn chế ố vàng", category: "ve-sinh-giay", summary: "Giày trắng cần xử lý vết bẩn sớm, dùng dụng cụ mềm và làm khô tránh nắng gắt. Chất liệu da, vải, lưới có cách xử lý khác nhau.", firstAction: "Tháo dây giày, phủi bụi khô và thử dung dịch ở vùng khuất trước.", serviceSlug: shoes },
  { slug: "ve-sinh-giay-vai", title: "Cách giặt giày vải, giày canvas không phai màu", category: "ve-sinh-giay", summary: "Giày vải cần tránh ngâm quá lâu và chà quá mạnh để hạn chế phai màu, bong keo. Làm khô chậm, thoáng khí giúp giữ form tốt hơn.", firstAction: "Tháo dây, dùng bàn chải mềm và không phơi trực tiếp dưới nắng gắt.", serviceSlug: shoes },
  { slug: "ve-sinh-giay-the-thao", title: "Vệ sinh giày thể thao sau khi tập: sạch mồ hôi và mùi", category: "ve-sinh-giay", summary: "Giày thể thao thường giữ mồ hôi ở lót và mũi giày. Làm sạch sớm, hong khô kỹ và xử lý lót riêng giúp hạn chế mùi.", firstAction: "Lấy lót giày ra hong thoáng, phủi bụi đất khô trước khi vệ sinh.", serviceSlug: shoes },
  { slug: "giat-giay-hoc-sinh", title: "Giặt giày học sinh bao lâu một lần và làm sao nhanh khô?", category: "ve-sinh-giay", summary: "Giày học sinh cần vệ sinh khi bám bẩn, có mùi hoặc đi mưa. Làm khô hoàn toàn quan trọng hơn việc giặt thường xuyên.", firstAction: "Giũ bùn, tháo dây và nhét giấy sạch hút ẩm để giữ form khi hong.", serviceSlug: shoes },
  { slug: "giay-bi-hoi", title: "Giày bị hôi phải làm sao? Cách xử lý lót giày và mùi ẩm", category: "ve-sinh-giay", summary: "Mùi hôi thường đến từ mồ hôi, vi khuẩn và giày không khô. Cần làm sạch lót, hong khô kỹ và thay đổi thói quen bảo quản.", firstAction: "Lấy lót giày ra, hong ở nơi thoáng và không cất giày khi còn ẩm.", serviceSlug: shoes },
  { slug: "giay-bi-moc", title: "Giày bị mốc có giặt được không? Khi nào nên mang đi vệ sinh", category: "ve-sinh-giay", summary: "Mốc trên giày cần xử lý sớm nhưng không nên chà mạnh khi chưa biết chất liệu. Da, da lộn và vải cần phương án khác nhau.", firstAction: "Đeo găng khi xử lý, để giày nơi thoáng và chụp ảnh tình trạng trước khi dùng hóa chất.", serviceSlug: shoes, risk: "high" },
  { slug: "de-giay-bi-o-vang", title: "Đế giày trắng bị ố vàng: nguyên nhân và cách xử lý an toàn", category: "ve-sinh-giay", summary: "Đế giày có thể ố do bụi, oxy hóa hoặc phơi sai. Tránh dùng chất tẩy mạnh vì có thể ảnh hưởng cao su và phần thân giày.", firstAction: "Lau bụi bằng khăn ẩm, thử ở một điểm nhỏ và không ngâm cả đôi khi chưa rõ vật liệu.", serviceSlug: shoes, risk: "high" },
  { slug: "giay-dinh-bun", title: "Giày dính bùn đất sau mưa: làm sạch thế nào để không hỏng keo?", category: "ve-sinh-giay", summary: "Bùn đất nên được để khô bớt rồi phủi nhẹ trước. Ngâm lâu hoặc sấy nóng có thể làm hỏng keo và biến dạng giày.", firstAction: "Để bùn khô bớt, dùng bàn chải mềm phủi từ ngoài vào và tránh chà phần keo.", serviceSlug: shoes },
  { slug: "tay-vet-mau-tren-ao-trang", title: "Cách tẩy vết máu mới và khô trên áo trắng an toàn", category: "tay-vet-ban", summary: "Vết máu nên được xử lý bằng nước lạnh càng sớm càng tốt. Nước nóng và chà xát mạnh có thể làm vết bám sâu hơn vào sợi vải.", firstAction: "Thấm vết bằng nước lạnh từ mặt trái vải; không dùng nước nóng và không trộn hóa chất.", serviceSlug: laundry, risk: "high" },
  { slug: "ao-trang-bi-o-vang", title: "Áo trắng bị ố vàng lâu ngày: nguyên nhân và cách làm sáng lại", category: "tay-vet-ban", summary: "Ố vàng có thể do mồ hôi, cặn sản phẩm hoặc cất đồ khi chưa sạch khô. Cần thử ở vùng kín và xem nhãn vải trước khi xử lý.", firstAction: "Xác định vùng ố, thử xử lý ở mép trong áo và tránh tẩy quá mạnh trên vải mỏng.", serviceSlug: laundry },
  { slug: "tay-vet-mo-hoi-o-nach-ao", title: "Cách tẩy vết mồ hôi và ố vàng ở nách áo", category: "tay-vet-ban", summary: "Vết mồ hôi ở nách thường cần xử lý sớm và nhẹ tay, nhất là với áo màu. Chất liệu mỏng hoặc có in hình cần thận trọng.", firstAction: "Lộn trái áo, làm ẩm vùng vết bẩn và thử ở một điểm kín trước.", serviceSlug: laundry },
  { slug: "tay-vet-dau-an-tren-quan-ao", title: "Quần áo dính dầu ăn: xử lý ngay và khi vết đã khô", category: "tay-vet-ban", summary: "Vết dầu cần được thấm hút trước khi giặt để không lan rộng. Tránh xả nước nóng ngay vì có thể làm dầu bám chắc hơn trên một số vải.", firstAction: "Dùng giấy sạch thấm bớt dầu, không chà mạnh và không cho vào máy khi vết còn đậm.", serviceSlug: laundry },
  { slug: "tay-vet-nhot-xe-tren-quan-ao", title: "Cách xử lý vết nhớt xe trên quần áo mà không làm lem rộng", category: "tay-vet-ban", summary: "Nhớt xe là vết dầu khó xử lý và dễ loang. Không nên dùng dung môi không rõ thành phần trên vải hoặc gần nguồn lửa.", firstAction: "Thấm bớt phần nhớt bằng giấy, tách món đồ khỏi các đồ khác và gửi ảnh để hỏi hướng xử lý.", serviceSlug: laundry, risk: "high" },
  { slug: "tay-vet-nuoc-sot-tren-ao", title: "Áo dính nước sốt, tương ớt: cách xử lý theo áo trắng và áo màu", category: "tay-vet-ban", summary: "Nước sốt thường có màu và dầu. Xử lý sớm bằng thao tác thấm, xả nhẹ giúp hạn chế vết bám; áo màu cần thử vùng kín trước.", firstAction: "Gạt phần đặc bằng vật cùn, thấm từ ngoài vào trong và không chà vòng tròn.", serviceSlug: laundry },
  { slug: "tay-vet-nuoc-mam-tren-quan-ao", title: "Quần áo dính nước mắm: xử lý cả vết màu lẫn mùi", category: "tay-vet-ban", summary: "Nước mắm có thể để lại mùi nếu vải không được xả và làm khô kỹ. Xử lý sớm, giặt theo nhãn và hong thoáng là quan trọng.", firstAction: "Xả nhẹ vùng dính bằng nước mát, không ủ kín đồ ướt và không trộn chất tẩy.", serviceSlug: laundry },
  { slug: "tay-vet-tra-tren-ao", title: "Cách tẩy vết trà mới và vết trà đã khô trên quần áo", category: "tay-vet-ban", summary: "Vết trà mới thường dễ xử lý hơn vết đã khô. Thấm và xả nhẹ từ mặt trái giúp hạn chế vết lan; cần thận trọng với vải màu.", firstAction: "Thấm phần trà thừa, xả từ mặt trái vải và thử sản phẩm giặt ở vùng kín.", serviceSlug: laundry },
  { slug: "tay-vet-sua-tren-quan-ao", title: "Quần áo dính sữa: làm sạch vết protein và mùi chua", category: "tay-vet-ban", summary: "Sữa cần được xả sớm bằng nước mát để hạn chế mùi chua và vết protein bám lại. Không nên dùng nhiệt cao trước khi vết sạch.", firstAction: "Xả nước mát từ mặt trái, giặt theo nhãn và làm khô hoàn toàn sau đó.", serviceSlug: laundry },
  { slug: "tay-vet-socola-tren-quan-ao", title: "Cách tẩy vết socola trên quần áo trắng và quần áo màu", category: "tay-vet-ban", summary: "Socola có chất béo và màu nên cần gạt phần đặc, thấm nhẹ rồi giặt theo nhãn. Áo trắng và áo màu cần thử riêng ở vùng kín.", firstAction: "Gạt socola khô bằng vật cùn, không miết sâu vào sợi vải và không dùng nước quá nóng.", serviceSlug: laundry },
  { slug: "tay-vet-trai-cay-tren-quan-ao", title: "Quần áo dính nước trái cây: xử lý màu nhuộm tự nhiên thế nào?", category: "tay-vet-ban", summary: "Nước trái cây có thể để lại màu rõ trên vải sáng. Xử lý nhanh, xả nhẹ và tránh nhiệt cao giúp hạn chế vết bám.", firstAction: "Thấm nước trái cây bằng khăn sạch, xả từ mặt trái và không sấy khi vết còn thấy rõ.", serviceSlug: laundry },
  { slug: "tay-vet-co-tren-quan-ao", title: "Cách tẩy vết cỏ xanh trên quần áo thể thao và đồng phục", category: "tay-vet-ban", summary: "Vết cỏ xanh có sắc tố và dễ thấy trên đồ sáng màu. Cần xử lý từng bước, thử vùng kín và không chà mạnh trên logo/in hình.", firstAction: "Phủi cỏ khô, làm ẩm nhẹ vùng vết và thử sản phẩm giặt ở chỗ kín.", serviceSlug: laundry },
  { slug: "tay-vet-bun-dat-tren-quan-ao", title: "Quần áo dính bùn đất: nên để khô hay giặt ngay?", category: "tay-vet-ban", summary: "Bùn đất nên được giũ hoặc để khô bớt trước khi phủi; chà lúc còn ướt dễ làm bùn ăn sâu vào vải.", firstAction: "Để bùn se lại, phủi nhẹ bên ngoài rồi xả từ mặt trái vải.", serviceSlug: laundry },
  { slug: "quan-ao-bi-moc-den", title: "Quần áo bị mốc đen, đốm li ti: có cứu được không?", category: "tay-vet-ban", summary: "Mốc có thể để lại vết lâu và gây mùi. Không nên mặc khi chưa xử lý; vải mỏng, đồ màu hoặc vết lâu ngày cần thận trọng.", firstAction: "Đeo găng, để đồ thoáng, tránh giũ trong phòng kín và không trộn các chất tẩy.", serviceSlug: laundry, risk: "high" },
  { slug: "tay-keo-dinh-tren-quan-ao", title: "Keo dính trên quần áo: cách nhận biết loại keo trước khi xử lý", category: "tay-vet-ban", summary: "Keo có nhiều loại và dùng sai dung môi có thể làm hỏng màu, sợi hoặc lớp in. Khi chưa biết loại keo, nên dừng ở bước nhận diện và thử vùng kín.", firstAction: "Không đổ dung môi trực tiếp; chụp cận vết keo và đọc nhãn vải trước khi xử lý.", serviceSlug: laundry, risk: "high" },
  { slug: "keo-cao-su-dinh-quan-ao", title: "Kẹo cao su dính vào quần áo: cách gỡ mà không rách vải", category: "tay-vet-ban", summary: "Kẹo cao su nên được làm cứng rồi gỡ từ từ bằng vật cùn. Kéo mạnh hoặc dùng vật sắc có thể làm xước, rách vải.", firstAction: "Làm cứng phần kẹo, gỡ từng ít bằng vật cùn và không giật mạnh sợi vải.", serviceSlug: laundry },
  { slug: "tay-son-tren-quan-ao", title: "Quần áo dính sơn nước hoặc sơn dầu: khi nào không nên tự tẩy?", category: "tay-vet-ban", summary: "Sơn nước và sơn dầu cần xử lý khác nhau. Dùng dung môi sai có thể làm phai, hỏng sợi và tạo nguy cơ cháy; vết lớn nên dừng tự xử lý.", firstAction: "Không sấy hoặc đưa gần lửa; chụp nhãn lon sơn và nhãn vải trước khi hỏi hướng xử lý.", serviceSlug: laundry, risk: "high" },
  { slug: "quan-ao-co-mui-am-moc", title: "Quần áo có mùi ẩm mốc sau khi giặt: nguyên nhân và cách khử", category: "cham-soc-quan-ao", summary: "Mùi ẩm mốc thường xuất hiện khi đồ, máy giặt hoặc nơi phơi chưa khô sạch. Cần giặt lại phù hợp và làm khô hoàn toàn trước khi cất.", firstAction: "Không xịt nước hoa để che mùi; tìm nguồn ẩm, giặt lại và hong đồ ở nơi thông thoáng.", serviceSlug: laundry },
  { slug: "quan-ao-phoi-khong-kho-bi-hoi", title: "Quần áo phơi lâu không khô và bị hôi trong mùa mưa phải làm sao?", category: "cham-soc-quan-ao", summary: "Đồ phơi lâu trong điều kiện ẩm dễ có mùi. Đừng cất hoặc mặc khi còn ẩm; giặt lại nếu mùi bám rõ rồi chọn cách làm khô phù hợp.", firstAction: "Kiểm tra vùng dày còn ẩm, giặt lại khi có mùi và tăng thông gió nơi phơi.", serviceSlug: laundry },
  { slug: "quan-ao-am-mui-khoi", title: "Cách khử mùi khói thuốc, khói bếp bám trên quần áo", category: "cham-soc-quan-ao", summary: "Mùi khói có thể bám vào sợi vải, nhất là đồ dày. Thông gió, giặt theo nhãn và làm khô kỹ thường hiệu quả hơn việc chỉ xịt hương thơm.", firstAction: "Treo đồ nơi thoáng trước, không cất chung với đồ sạch và xử lý theo nhãn vải.", serviceSlug: laundry },
  { slug: "quan-ao-dinh-nuoc-tieu", title: "Cách xử lý mùi nước tiểu trên quần áo, ga giường và chăn", category: "cham-soc-quan-ao", summary: "Nước tiểu nên được xả sớm bằng nước mát, giặt theo nhãn và làm khô hoàn toàn. Với đồ dày hoặc vết bám lâu, cần kiểm tra kỹ trước khi cất.", firstAction: "Xả vùng dính bằng nước mát, tách đồ ra khỏi mẻ khác và không dùng nhiệt cao trước khi giặt sạch.", serviceSlug: laundry },
  { slug: "quan-ao-bi-lem-mau", title: "Quần áo bị lem màu khi giặt: xử lý sớm và tránh làm hỏng thêm", category: "cham-soc-quan-ao", summary: "Khi đồ bị lem màu, cần tách khỏi mẻ ngay và tránh sấy hoặc phơi nóng. Khả năng xử lý phụ thuộc màu gốc, thuốc nhuộm và thời điểm phát hiện.", firstAction: "Tách ngay đồ trắng và đồ màu, không sấy khi còn lem và thử ở vùng kín trước khi xử lý.", serviceSlug: laundry }
];

export function getGuide(slug: string) {
  return guides.find((guide) => guide.slug === slug);
}

export function getGuidesByCategory(category: GuideCategory) {
  return guides.filter((guide) => guide.category === category);
}
