import type { Guide } from "@/config/guides";

export type GuideAdvice = {
  steps: [string, string, string];
  avoid: string;
  stopWhen: string;
  tags: string[];
};

const advice: Record<string, GuideAdvice> = {
  "gia-giat-say-can-tho": { steps: ["Cân riêng quần áo thường, đồ dày và món cần xử lý đặc biệt.", "Đối chiếu lựa chọn: giặt phơi từ 3kg là 7K/kg, giặt sấy từ 3kg là 9K/kg; dưới 3kg là 35K/lần.", "Gửi số kg ước tính và ảnh món đặc biệt để tiệm chốt giá trước khi nhận."], avoid: "Không cộng chung giày, chăn bông, rèm hoặc tẩy điểm vào giá quần áo tính theo kg.", stopWhen: "Nếu chưa rõ chất liệu, số lượng hoặc mức độ vết bẩn, hãy yêu cầu báo giá thực tế thay vì tự ước tính.", tags: ["gia", "bao-gia", "dich-vu"] },
  "giat-ui-giao-nhan-tan-noi-can-tho": { steps: ["Gửi địa chỉ, loại đồ và số lượng ước tính qua Zalo.", "Chờ tiệm xác nhận đơn có nằm trong bán kính freeship 3km hay không.", "Chốt giá, giờ nhận và giờ trả trước khi giao đồ."], avoid: "Không mặc định mọi khu vực Cần Thơ đều được giao nhận miễn phí.", stopWhen: "Khu vực ngoài 3km hoặc đơn có đồ đặc biệt cần được DN House xác nhận riêng.", tags: ["giao-nhan", "khu-vuc", "dich-vu"] },
  "tiem-giat-ui-gan-day": { steps: ["Kiểm tra địa chỉ, giờ mở cửa và số điện thoại có công khai hay không.", "Xem bảng giá, phạm vi giao nhận và cách tiệm báo giá món đặc biệt.", "Gửi ảnh một món khó xử lý để đánh giá cách tư vấn trước khi giao cả đơn."], avoid: "Không chọn chỉ dựa trên lời hứa sạch tuyệt đối hoặc giá thấp nhưng không nói rõ cách tính.", stopWhen: "Nếu tiệm không xác nhận giá, thời gian hoặc trách nhiệm với đồ đặc biệt, nên hỏi lại trước khi gửi.", tags: ["bao-gia", "uy-tin", "dich-vu"] },
  "giat-say-lay-lien-can-tho": { steps: ["Báo chính xác thời điểm bạn cần nhận lại đồ.", "Cho biết số kg và tách món dày, vết bẩn hoặc đồ phải giặt tay.", "Chỉ xem là đơn gấp sau khi tiệm xác nhận lịch máy và thời gian làm khô."], avoid: "Không dựa vào một thời gian cố định vì đồ dày và đơn có tẩy điểm cần lâu hơn.", stopWhen: "Nếu thời gian yêu cầu không đủ để đồ khô hoàn toàn, nên đổi lịch nhận hoặc chọn phương án khác.", tags: ["thoi-gian", "don-gap", "dich-vu"] },
  "giat-say-mua-mua-can-tho": { steps: ["Xem nhãn để biết món đồ có phù hợp sấy máy không.", "Chọn giặt sấy cho đồ thường cần khô nhanh; chọn phơi tự nhiên cho món không chịu nhiệt.", "Kiểm tra cổ áo, cạp quần và đường may dày trước khi cất."], avoid: "Không cất hoặc xịt thơm để che mùi khi bên trong vải vẫn còn ẩm.", stopWhen: "Đồ có mùi sau khi đã khô cần được giặt lại và kiểm tra nguồn ẩm, không chỉ sấy thêm.", tags: ["mua-mua", "mui-am", "lam-kho"] },
  "giat-do-sinh-vien-can-tho": { steps: ["Gom đủ từ 3kg nếu muốn dùng mức giá tính theo kg.", "Tách đồ trắng, đồ ra màu, khăn và món có vết bẩn rõ.", "Kiểm tra túi quần áo và ghi chú món cần giữ form trước khi giao."], avoid: "Không nhồi chung giày hoặc món phải giặt tay vào mẻ quần áo thường.", stopWhen: "Đồ có logo dán, vải mỏng hoặc vết khó nên được chỉ rõ cho tiệm trước.", tags: ["gia", "phan-loai", "dich-vu"] },
  "giat-do-cong-so-can-tho": { steps: ["Đọc nhãn áo sơ mi, quần tây và váy trước khi chọn cách giặt.", "Đánh dấu vết ở cổ, tay áo và khu vực dễ bỏ sót.", "Lấy đồ ra khi vừa khô và treo hoặc gấp ngay để hạn chế nhăn."], avoid: "Không sấy nhiệt cao áo có lớp dựng, keo ép hoặc chi tiết dễ biến dạng.", stopWhen: "Đồ ghi giặt khô hoặc có cấu trúc đặc biệt cần được kiểm tra riêng.", tags: ["cong-so", "it-nhan", "nhan-vai"] },
  "giat-dong-phuc-can-tho": { steps: ["Chia đồng phục trắng, màu đậm và đồ có in/logo thành nhóm.", "Kiểm đếm theo người hoặc theo bộ trước khi bàn giao.", "Chốt số lượng, giá và thời điểm trả đối với đơn nhiều đồ."], avoid: "Không dùng nhiệt cao trực tiếp lên hình in chuyển nhiệt hoặc logo dán.", stopWhen: "Đơn số lượng lớn hoặc cần trả đồng loạt phải được tiệm xác nhận năng lực và lịch trước.", tags: ["dong-phuc", "so-luong-lon", "phan-loai"] },
  "giat-do-em-be-can-tho": { steps: ["Tách đồ em bé khỏi đồ bẩn nặng của người lớn.", "Dùng lượng sản phẩm đúng hướng dẫn và xả kỹ để hạn chế cặn.", "Làm khô hoàn toàn rồi kiểm tra mùi trước khi cất."], avoid: "Không tự suy đoán sản phẩm nào phù hợp nếu bé có tiền sử kích ứng hoặc da đang tổn thương.", stopWhen: "Nếu bé có phản ứng da, hãy ngừng dùng món đồ và hỏi ý kiến chuyên môn; DN House không thay thế tư vấn y tế.", tags: ["em-be", "can-giat", "nhay-cam"] },
  "giat-do-so-luong-lon-can-tho": { steps: ["Lập số lượng theo nhóm quần áo, khăn, chăn và món đặc biệt.", "Đánh dấu đồ cần giặt tay, tẩy điểm hoặc trả gấp.", "Chốt cách cân, đơn giá và biên nhận trước khi giao."], avoid: "Không bàn giao một khối đồ không kiểm đếm nếu có nhiều người hoặc nhiều bộ giống nhau.", stopWhen: "Đơn lớn cần lịch trả cố định phải được DN House xác nhận trước khi vận chuyển.", tags: ["so-luong-lon", "bao-gia", "kiem-dem"] },
  "giat-rem-cua-can-tho": { steps: ["Chụp toàn bộ rèm, nhãn vải và kiểu khoen/móc trước khi tháo.", "Tháo phụ kiện rời, kiểm tra đường may mục và ghi lại từng tấm.", "Giặt theo nhãn và chỉ lắp lại khi rèm đã khô hoàn toàn."], avoid: "Không kéo giật rèm cũ, ngâm khoen kim loại hoặc dùng nhiệt khi chưa rõ chất liệu.", stopWhen: "Rèm mục nắng, có lớp cản sáng bong hoặc không còn nhãn cần được kiểm tra trước; giá niêm yết là 25K/kg.", tags: ["rem", "do-day", "gia"] },
  "giat-topper-can-tho": { steps: ["Xác định topper là foam, cao su, bông hay loại có vỏ tháo rời.", "Xử lý riêng phần vỏ theo nhãn; thấm hút cục bộ phần lõi nếu nhà sản xuất cho phép.", "Đặt phẳng và làm khô sâu trước khi bọc hoặc sử dụng lại."], avoid: "Không ngâm hoặc cho cả lõi topper vào máy khi chưa biết cấu tạo.", stopWhen: "Lõi hút nước, mốc sâu, có mùi kéo dài hoặc không có hướng dẫn chăm sóc cần được kiểm tra thực tế; website chưa niêm yết giá topper.", tags: ["topper", "mui-am", "rui-ro-cao"] },
  "giat-goi-can-tho": { steps: ["Kiểm tra gối có tháo được vỏ và ruột thuộc loại nào.", "Khâu chỗ rách nhỏ, phân bổ gối đều trong máy nếu nhãn cho phép giặt.", "Làm khô hoàn toàn, bóp kiểm tra phần lõi trước khi dùng lại."], avoid: "Không vắt xoắn hoặc cất gối khi phần giữa còn ẩm.", stopWhen: "Gối foam/cao su, ruột vón nặng hoặc có mốc sâu cần làm theo hướng dẫn nhà sản xuất; chưa có giá gối riêng trên bảng giá.", tags: ["goi", "do-day", "lam-kho"] },
  "giat-ga-giuong-can-tho": { steps: ["Dùng mốc khoảng mỗi tuần làm điểm bắt đầu, rồi điều chỉnh theo mồ hôi, thú nuôi và tình trạng da.", "Tách ga sáng và màu đậm; xử lý vết mới trước khi giặt.", "Làm khô hoàn toàn và thay ngay khi có mùi, ẩm hoặc vết bẩn."], avoid: "Không đợi đến khi nhìn thấy bẩn mới thay ga trong điều kiện nóng ẩm.", stopWhen: "Ga có vết sinh học, mốc hoặc chất liệu đặc biệt cần xử lý riêng; giá chăn/drap tại DN House là 15K–20K/kg.", tags: ["ga-giuong", "tan-suat", "chan-drap"] },
  "giat-chan-bong-can-tho": { steps: ["Kiểm tra nhãn, đường may và khả năng chứa của máy.", "Giặt đúng tải để chăn có khoảng chuyển động, không bị ép thành khối.", "Làm khô kỹ và đảo vị trí để ruột chăn tơi đều."], avoid: "Không nhồi chăn vào máy quá nhỏ hoặc cất khi lõi vẫn lạnh ẩm.", stopWhen: "Chăn rách, ruột vón sẵn hoặc nhãn cấm giặt máy cần kiểm tra riêng; giá chăn bông niêm yết là 25K/kg.", tags: ["chan-bong", "do-day", "lam-kho"] },
  "giat-thu-bong-can-tho": { steps: ["Kiểm tra pin, hộp nhạc, phụ kiện dán và đường may.", "Tháo phần rời; ưu tiên làm sạch nhẹ theo nhãn thay vì ngâm toàn bộ.", "Nắn lại form và làm khô sâu tới phần ruột."], avoid: "Không cho thú có linh kiện điện tử, hạt độn hoặc keo dán vào máy.", stopWhen: "Thú bông không có nhãn, ruột mục hoặc phụ kiện không tháo được cần gửi ảnh để DN House xác nhận có nhận xử lý hay không.", tags: ["thu-bong", "giu-form", "do-day"] },
  "giat-ao-khoac-can-tho": { steps: ["Đóng khóa, tháo phụ kiện rời và đọc nhãn lớp ngoài/lớp lót.", "Xử lý vết bẩn cục bộ trước, dùng chu trình phù hợp nếu nhãn cho phép.", "Làm khô theo nhãn và phân bổ lại lớp bông nếu cần."], avoid: "Không dùng nước xả hoặc nhiệt cao với lớp phủ chống nước khi nhà sản xuất không cho phép.", stopWhen: "Áo có lông, da, lớp màng kỹ thuật hoặc ghi giặt khô cần được kiểm tra chuyên biệt.", tags: ["ao-khoac", "do-day", "nhan-vai"] },
  "giat-balo-can-tho": { steps: ["Lấy hết đồ trong mọi ngăn, hút hoặc phủi bụi khô.", "Kiểm tra khung, da, lớp chống nước, hình in và khóa kéo.", "Làm sạch từng vùng theo nhãn rồi phơi mở ngăn ở nơi thoáng."], avoid: "Không ngâm cả balo có khung, cổng sạc, da hoặc lớp phủ chưa xác định.", stopWhen: "Balo mốc sâu, bong lớp phủ hoặc không có hướng dẫn chăm sóc cần gửi ảnh; bảng giá hiện chưa có mục balo riêng.", tags: ["balo", "mui-am", "rui-ro-cao"] },
  "giat-non-can-tho": { steps: ["Xem vành nón làm từ nhựa, bìa hay vật liệu không xác định.", "Làm sạch từng vùng bằng khăn/bàn chải mềm theo nhãn.", "Định hình và hong tự nhiên trên vật đỡ phù hợp."], avoid: "Không vắt xoắn, gập vành hoặc phơi nắng gắt.", stopWhen: "Nón có vành bìa, chữ ký, hình in dễ bong hoặc không rõ vật liệu cần gửi ảnh để xác nhận trước.", tags: ["non", "giu-form", "giat-tay"] },
  "giat-man-chong-muoi": { steps: ["Giũ bụi ngoài trời và kiểm tra lỗ rách, móc còn sót.", "Gấp lưới vào túi giặt hoặc giặt tay nhẹ theo nhãn.", "Treo trải rộng, tránh điểm sắc và để khô hoàn toàn."], avoid: "Không giặt chung với khóa kéo, móc kim loại hoặc đồ nặng.", stopWhen: "Lưới đã mục, rách nhiều hoặc có lớp xử lý đặc biệt cần làm theo hướng dẫn nhà sản xuất.", tags: ["man-mung", "vai-mong", "giat-tay"] },
  "ve-sinh-giay-trang": { steps: ["Tháo dây và lót, phủi sạch bụi khô trên thân và đế.", "Làm sạch theo từng chất liệu bằng dụng cụ mềm, bắt đầu ở vùng khuất.", "Thấm bớt nước, giữ form và hong nơi thoáng tránh nắng gắt."], avoid: "Không dùng chất tẩy mạnh cho toàn bộ đôi giày hoặc phơi dưới nắng trực tiếp.", stopWhen: "Giày có da lộn, da thật, keo bong hoặc ố do oxy hóa cần kiểm tra riêng; vệ sinh giày tại DN House là 50K/đôi.", tags: ["giay-trang", "o-vang", "giay"] },
  "ve-sinh-giay-vai": { steps: ["Tháo dây/lót và thử độ bền màu ở mép trong.", "Chà nhẹ theo chiều vải, xử lý từng mảng thay vì ngâm lâu.", "Nhét giấy sạch giữ form và hong ở nơi thoáng."], avoid: "Không dùng bàn chải cứng, vắt xoắn hoặc sấy nóng phần keo.", stopWhen: "Màu ra trên khăn thử, thân giày bong keo hoặc có chi tiết da cần dừng; giá vệ sinh tham khảo 50K/đôi.", tags: ["giay-vai", "phai-mau", "giay"] },
  "ve-sinh-giay-the-thao": { steps: ["Tháo lót và dây để xử lý mồ hôi ở từng phần.", "Phủi đất khô rồi làm sạch thân giày theo vật liệu.", "Hong mở miệng giày đến khi lót và mũi khô hoàn toàn."], avoid: "Không che mùi bằng xịt thơm khi lót vẫn ẩm hoặc sấy sát nguồn nhiệt.", stopWhen: "Mùi quay lại nhanh, keo yếu hoặc giày có cấu trúc kỹ thuật đặc biệt cần kiểm tra; DN House vệ sinh giày 50K/đôi.", tags: ["giay-the-thao", "mui-hoi", "giay"] },
  "giat-giay-hoc-sinh": { steps: ["Vệ sinh khi giày có bùn, mùi hoặc sau khi đi mưa thay vì theo lịch cứng.", "Tháo dây/lót, phủi bùn khô rồi làm sạch nhẹ.", "Chuẩn bị đôi thay thế để giày có đủ thời gian khô hoàn toàn."], avoid: "Không mang giày còn ẩm và không sấy nóng để ép khô nhanh.", stopWhen: "Giày cần dùng ngay nhưng chưa khô hoặc có keo bong nên dừng; DN House vệ sinh giày 50K/đôi và xác nhận thời gian sau khi xem tình trạng.", tags: ["giay-hoc-sinh", "lam-kho", "mui-hoi"] },
  "giay-bi-hoi": { steps: ["Lấy lót và dây ra, kiểm tra phần nào còn ẩm hoặc bẩn.", "Làm sạch lót theo nhãn và lau bên trong bằng phương pháp phù hợp vật liệu.", "Hong từng phần hoàn toàn; luân phiên giày và tất sạch khi có thể."], avoid: "Không chỉ xịt nước hoa hoặc cất giày ẩm trong hộp kín.", stopWhen: "Mùi kèm mốc, vật liệu mục hoặc kích ứng chân cần xử lý nguyên nhân thay vì tiếp tục che mùi.", tags: ["mui-hoi", "lot-giay", "giay"] },
  "giay-bi-moc": { steps: ["Mang giày ra nơi thoáng, đeo găng và tách khỏi các đôi khác.", "Xác định da, da lộn, vải hay vật liệu tổng hợp trước khi làm sạch.", "Xử lý thử vùng nhỏ, làm khô hoàn toàn và vệ sinh nơi cất giày."], avoid: "Không giũ mốc trong phòng kín hoặc đổ chất tẩy trực tiếp lên giày.", stopWhen: "Mốc ăn sâu, phủ diện rộng, vật liệu đổi màu hoặc người xử lý nhạy cảm với mốc cần dừng; hãy gửi ảnh để DN House đánh giá.", tags: ["giay-moc", "mui-am", "rui-ro-cao"] },
  "de-giay-bi-o-vang": { steps: ["Lau sạch bụi để phân biệt bẩn bề mặt với cao su đã oxy hóa.", "Thử sản phẩm phù hợp trên một điểm nhỏ của phần đế.", "Lau/rửa sạch phần dư và hong tránh nắng gắt."], avoid: "Không để hóa chất chạm thân giày hoặc kỳ vọng mọi vết oxy hóa đều trở lại trắng như mới.", stopWhen: "Đế giòn, nứt, đổi màu sâu hoặc thân giày nhạy cảm cần được kiểm tra trực tiếp.", tags: ["de-giay", "o-vang", "rui-ro-cao"] },
  "giay-dinh-bun": { steps: ["Để bùn se hoặc khô bớt rồi gõ/phủi phần rời.", "Tháo dây/lót và làm sạch từ phần ít bẩn tới phần nhiều bẩn.", "Thấm nước, giữ form và hong xa nguồn nhiệt."], avoid: "Không chà bùn ướt sâu vào lưới hoặc ngâm lâu phần keo.", stopWhen: "Bùn lẫn dầu, nước bẩn không rõ nguồn hoặc keo bắt đầu bong cần dừng tự xử lý.", tags: ["giay-bun", "mua-mua", "giay"] },
  "tay-vet-mau-tren-ao-trang": { steps: ["Xả nước lạnh từ mặt trái để đẩy vết ra ngoài.", "Dùng sản phẩm giặt có hướng dẫn phù hợp vết protein và nhãn vải; xử lý nhẹ rồi xả.", "Kiểm tra dưới ánh sáng trước khi giặt lại và chỉ làm khô khi vết đã hết."], avoid: "Không dùng nước nóng, chà mạnh hoặc trộn chất tẩy.", stopWhen: "Vết đã qua sấy, vải mỏng hoặc máu không rõ nguồn cần thận trọng; tẩy điểm tại DN House từ 15K–50K sau khi kiểm tra.", tags: ["vet-protein", "ao-trang", "rui-ro-cao"] },
  "ao-trang-bi-o-vang": { steps: ["Xác định ố ở nách/cổ, do cất lâu hay toàn bộ áo.", "Đọc nhãn và thử sản phẩm dành cho đồ trắng ở gấu trong.", "Xử lý theo hướng dẫn sản phẩm, xả kỹ và kiểm tra trước khi sấy."], avoid: "Không dùng chất tẩy clo cho mọi loại vải trắng; màu trắng không đồng nghĩa sợi vải chịu được tẩy mạnh.", stopWhen: "Vải mỏng, có pha màu/in hoặc ố đã làm yếu sợi cần dừng; tẩy điểm được báo giá 15K–50K.", tags: ["ao-trang", "o-vang", "vet-mo-hoi"] },
  "tay-vet-mo-hoi-o-nach-ao": { steps: ["Lộn trái và kiểm tra màu vải ở đường may trong.", "Làm ẩm, dùng sản phẩm giặt phù hợp rồi thao tác nhẹ từ rìa vào giữa.", "Xả kỹ, kiểm tra mùi/vết trước khi phơi hoặc sấy."], avoid: "Không chà mạnh vào nách áo màu hoặc dùng nhiệt khi vết còn vàng.", stopWhen: "Vải đổi màu, hình in bị ảnh hưởng hoặc sợi đã mục cần dừng xử lý.", tags: ["vet-mo-hoi", "o-vang", "ao-mau"] },
  "tay-vet-dau-an-tren-quan-ao": { steps: ["Thấm dầu bằng giấy sạch, đổi mặt giấy để không ép dầu trở lại.", "Xử lý cục bộ bằng sản phẩm giặt phù hợp nhãn vải.", "Giặt lại và kiểm tra cả hai mặt trước khi làm khô."], avoid: "Không chà vòng tròn, cho ngay vào máy cùng đồ khác hoặc sấy khi còn quầng dầu.", stopWhen: "Vết lan rộng, đã qua nhiệt hoặc nằm trên lụa/len/vải nhạy cảm cần dừng.", tags: ["vet-dau", "thuc-pham", "tay-diem"] },
  "tay-vet-nhot-xe-tren-quan-ao": { steps: ["Tách món đồ, thấm phần nhớt dư bằng giấy và bảo vệ bề mặt bên dưới.", "Đọc nhãn vải và nhãn sản phẩm; chỉ thử giải pháp phù hợp ở vùng kín.", "Xử lý từ ngoài vào giữa, xả/giặt riêng và kiểm tra trước khi làm khô."], avoid: "Không dùng xăng, dung môi không rõ thành phần hoặc thao tác gần lửa.", stopWhen: "Vết lớn, đã khô lâu, có mùi dung môi mạnh hoặc vải đổi màu cần dừng; gửi ảnh để báo tẩy điểm.", tags: ["vet-dau", "nhot-xe", "rui-ro-cao"] },
  "tay-vet-nuoc-sot-tren-ao": { steps: ["Gạt phần đặc bằng thìa hoặc vật cùn, không miết vào vải.", "Xả từ mặt trái bằng nước mát rồi xử lý phần dầu/màu theo nhãn.", "Với áo màu, thử vùng kín; kiểm tra trước khi sấy."], avoid: "Không chà vòng tròn hoặc dùng chất làm sáng của đồ trắng lên áo màu.", stopWhen: "Vết chứa dầu đã khô, áo có in hoặc màu ra trên khăn thử cần dừng.", tags: ["thuc-pham", "vet-dau", "ao-mau"] },
  "tay-vet-nuoc-mam-tren-quan-ao": { steps: ["Xả nước mát từ mặt trái càng sớm càng tốt.", "Giặt riêng vùng bẩn theo nhãn, chú ý cả vết màu lẫn phần gây mùi.", "Xả kỹ và hong thoáng đến khi khô hoàn toàn."], avoid: "Không ủ đồ ướt trong túi kín hoặc xịt hương để che mùi.", stopWhen: "Mùi còn sau một lần giặt hoặc đồ dày giữ ẩm cần giặt lại/kiểm tra trước khi cất.", tags: ["thuc-pham", "mui", "vet-protein"] },
  "tay-vet-tra-tren-ao": { steps: ["Thấm phần trà còn ướt, không kéo khăn qua vùng sạch.", "Xả từ mặt trái bằng nước phù hợp nhãn và xử lý nhẹ bằng sản phẩm giặt.", "Vết khô cần làm ẩm lại và có thể lặp từng chu kỳ thay vì tăng độ mạnh."], avoid: "Không sấy hoặc ủi khi còn thấy viền nâu.", stopWhen: "Vải màu ra màu, vết đã qua nhiều lần nhiệt hoặc chất liệu nhạy cảm cần dừng.", tags: ["do-uong", "vet-mau", "tay-diem"] },
  "tay-vet-sua-tren-quan-ao": { steps: ["Xả nước mát từ mặt trái để loại phần sữa chưa khô.", "Xử lý bằng sản phẩm giặt phù hợp vết protein và nhãn vải.", "Xả kỹ, kiểm tra mùi chua rồi làm khô hoàn toàn."], avoid: "Không dùng nước nóng hoặc sấy trước khi vết protein sạch.", stopWhen: "Vết đã chua lâu, nằm trong đệm/đồ dày hoặc vẫn có mùi sau khi khô cần xử lý sâu hơn.", tags: ["vet-protein", "mui", "thuc-pham"] },
  "tay-vet-socola-tren-quan-ao": { steps: ["Làm cứng nhẹ nếu cần rồi gạt phần socola bằng vật cùn.", "Xả từ mặt trái và xử lý riêng phần dầu/màu theo nhãn.", "Giặt lại, kiểm tra quầng trong ánh sáng trước khi làm khô."], avoid: "Không miết socola tan sâu vào sợi hoặc dùng nước quá nóng ngay từ đầu.", stopWhen: "Vết nằm trên lụa/len, áo màu phai hoặc đã qua sấy cần dừng.", tags: ["thuc-pham", "vet-dau", "vet-mau"] },
  "tay-vet-trai-cay-tren-quan-ao": { steps: ["Thấm phần nước quả, không kéo màu lan sang vùng sạch.", "Xả từ mặt trái rồi xử lý theo nhãn vải.", "Lặp thao tác nhẹ với vết khô và kiểm tra trước khi làm nóng."], avoid: "Không sấy/ủi khi màu vết vẫn còn hoặc tự dùng chất tẩy mạnh trên áo màu.", stopWhen: "Màu vải thay đổi, vết từ quả đậm đã khô lâu hoặc vải mỏng cần dừng.", tags: ["trai-cay", "vet-mau", "ao-mau"] },
  "tay-vet-co-tren-quan-ao": { steps: ["Phủi phần cỏ/đất khô và lộn mặt có vết ra ngoài.", "Làm ẩm rồi xử lý sắc tố từng vùng bằng sản phẩm phù hợp nhãn.", "Giặt lại và kiểm tra logo, đường may trước khi làm khô."], avoid: "Không chà mạnh lên hình in hoặc dùng nhiệt khi vệt xanh còn rõ.", stopWhen: "Vết trên đồng phục có logo dán, vải màu ra màu hoặc đã qua sấy cần dừng.", tags: ["vet-co", "dong-phuc", "vet-mau"] },
  "tay-vet-bun-dat-tren-quan-ao": { steps: ["Để bùn se/khô bớt rồi phủi phần rời ra ngoài.", "Xả từ mặt trái để đẩy đất khỏi sợi thay vì ép sâu hơn.", "Xử lý phần quầng còn lại theo nhãn rồi giặt riêng nếu cần."], avoid: "Không chà bùn khi còn ướt hoặc cho ngay vào mẻ đồ sạch.", stopWhen: "Bùn lẫn dầu, hóa chất hoặc nước bẩn không rõ nguồn cần tách và xử lý riêng.", tags: ["bun-dat", "mua-mua", "tay-diem"] },
  "quan-ao-bi-moc-den": { steps: ["Mang đồ ra nơi thoáng, đeo găng và tách khỏi đồ sạch.", "Đọc nhãn, thử vùng kín rồi xử lý bằng sản phẩm phù hợp loại vải.", "Giặt riêng, làm khô hoàn toàn và vệ sinh nơi cất đồ."], avoid: "Không giũ mốc trong phòng kín hoặc trộn thuốc tẩy với chất tẩy khác.", stopWhen: "Mốc phủ rộng, sợi mục, mùi không hết hoặc người xử lý nhạy cảm với mốc cần dừng.", tags: ["moc", "mui-am", "rui-ro-cao"] },
  "tay-keo-dinh-tren-quan-ao": { steps: ["Chụp và xác định keo nước, keo nóng, keo dán nhãn hay loại không rõ.", "Để keo ổn định rồi gỡ phần nổi bằng vật cùn nếu có thể.", "Đọc nhãn vải và thử phương án phù hợp ở đường may trong."], avoid: "Không đổ acetone/dung môi trực tiếp hoặc cạo bằng vật sắc.", stopWhen: "Không biết loại keo, vải có acetate/hình in hoặc màu thay đổi khi thử thì phải dừng.", tags: ["keo", "dung-moi", "rui-ro-cao"] },
  "keo-cao-su-dinh-quan-ao": { steps: ["Làm kẹo cứng lại bằng cách làm lạnh cục bộ.", "Dùng vật cùn nâng từng phần từ mép, không kéo sợi vải.", "Xử lý phần dầu/màu còn lại theo nhãn rồi giặt."], avoid: "Không dùng dao sắc, nước nóng hoặc giật mạnh miếng kẹo.", stopWhen: "Kẹo dính vào vải dệt thưa, len hoặc kéo biến dạng sợi thì nên dừng.", tags: ["keo-cao-su", "vat-ran", "tay-diem"] },
  "tay-son-tren-quan-ao": { steps: ["Đọc nhãn lon để phân biệt sơn nước, sơn dầu và chất pha loãng.", "Gạt phần sơn nổi bằng vật cùn, bảo vệ mặt sau của vải.", "Với sơn nước còn mới, xử lý theo hướng dẫn sản phẩm; các loại khác nên xin tư vấn trước."], avoid: "Không dùng dung môi tùy ý, không sấy và không thao tác gần lửa.", stopWhen: "Sơn dầu/không rõ loại, vết lớn, đã khô hoặc vải nhạy cảm cần dừng tự tẩy.", tags: ["son", "dung-moi", "rui-ro-cao"] },
  "quan-ao-co-mui-am-moc": { steps: ["Tìm nguồn mùi ở đồ, máy giặt, giỏ đồ hoặc nơi phơi.", "Giặt lại theo nhãn thay vì chỉ thêm hương thơm.", "Tăng thông gió và kiểm tra vùng dày đã khô trước khi cất."], avoid: "Không cất đồ còn ẩm hoặc dùng nước hoa để che mùi.", stopWhen: "Có đốm mốc, sợi mục hoặc mùi quay lại dù đã làm khô thì cần xử lý nguyên nhân.", tags: ["mui-am", "mua-mua", "lam-kho"] },
  "quan-ao-phoi-khong-kho-bi-hoi": { steps: ["Tách đồ còn ẩm, không để chồng thành đống.", "Giặt lại nếu đã có mùi rồi vắt đúng tải.", "Tạo khoảng cách khi phơi, tăng gió hoặc chọn sấy nếu nhãn cho phép."], avoid: "Không cất, mặc hoặc chỉ sấy nóng đồ đã có mùi mà chưa giặt lại.", stopWhen: "Đồ dày không thể khô sâu trong điều kiện hiện tại nên chuyển sang phương án làm khô phù hợp.", tags: ["mui-am", "mua-mua", "lam-kho"] },
  "quan-ao-am-mui-khoi": { steps: ["Treo tách biệt ở nơi thoáng để giảm mùi bám bề mặt.", "Đọc nhãn và giặt bằng chu trình phù hợp loại vải.", "Làm khô hoàn toàn; lặp lại chu trình nhẹ nếu đồ dày còn mùi."], avoid: "Không xịt hương rồi cất chung với đồ sạch.", stopWhen: "Đồ có muội, dầu bếp hoặc mùi cháy do tiếp xúc hóa chất cần xử lý như vết bẩn, không chỉ khử mùi.", tags: ["mui-khoi", "mui", "do-day"] },
  "quan-ao-dinh-nuoc-tieu": { steps: ["Xả nước mát từ mặt trái và tách khỏi mẻ đồ khác.", "Giặt theo nhãn, chú ý vùng đường may hoặc lõi chăn giữ chất lỏng.", "Xả kỹ và làm khô hoàn toàn rồi mới kiểm tra lại mùi."], avoid: "Không dùng nhiệt cao trước khi giặt sạch hoặc trộn nhiều chất khử mùi.", stopWhen: "Vết ngấm sâu vào chăn/đệm, đã khô lâu hoặc vẫn còn mùi cần kiểm tra riêng.", tags: ["mui", "vet-protein", "chan-drap"] },
  "quan-ao-bi-lem-mau": { steps: ["Tách món bị lem ngay khi còn ướt và giữ lại món gây ra màu nếu biết.", "Đọc nhãn cả hai món, thử phương án ở vùng kín.", "Xử lý sớm theo loại vải rồi kiểm tra trước khi phơi nóng hoặc sấy."], avoid: "Không sấy, ủi hoặc dùng chất tẩy đồ trắng lên quần áo màu.", stopWhen: "Màu gốc tiếp tục ra, vải có nhiều màu hoặc đã qua nhiệt cần dừng để tránh hỏng thêm.", tags: ["lem-mau", "ao-mau", "rui-ro"] }
};

export function getGuideAdvice(slug: string) {
  return advice[slug];
}

export function getGuideServiceFacts(guide: Guide) {
  if (guide.serviceSlug === "ve-sinh-giay-can-tho") {
    return {
      title: "Vệ sinh giày tại DN House",
      facts: ["Giá tham khảo 50K/đôi", "Có làm sạch và khử mùi", "Gửi ảnh để tiệm xác nhận tình trạng và thời gian"]
    };
  }

  if (guide.category === "tay-vet-ban" || guide.slug === "quan-ao-bi-lem-mau") {
    return {
      title: "Tẩy điểm tại DN House",
      facts: ["Tẩy điểm 15K–50K", "Tẩy toàn bộ: báo giá trực tiếp", "Tiệm kiểm tra chất liệu và tình trạng trước khi làm"]
    };
  }

  if (guide.slug === "giat-rem-cua-can-tho") {
    return { title: "Giặt rèm tại DN House", facts: ["Giá tham khảo 25K/kg", "Cần xem chất liệu và tình trạng rèm", "Báo giá trước khi làm"] };
  }

  if (guide.slug === "giat-chan-bong-can-tho") {
    return { title: "Giặt chăn bông tại DN House", facts: ["Giá tham khảo 25K/kg", "Kiểm tra độ dày và tình trạng trước", "Báo thời gian dự kiến khi nhận đồ"] };
  }

  if (["giat-ga-giuong-can-tho", "quan-ao-dinh-nuoc-tieu"].includes(guide.slug)) {
    return { title: "Giặt chăn, drap tại DN House", facts: ["Chăn/drap 15K–20K/kg", "Đồ dày được kiểm tra trước", "Báo giá trước khi làm"] };
  }

  if (["giat-topper-can-tho", "giat-goi-can-tho", "giat-thu-bong-can-tho", "giat-balo-can-tho", "giat-non-can-tho", "giat-man-chong-muoi"].includes(guide.slug)) {
    return {
      title: "Món này chưa có giá niêm yết riêng",
      facts: ["Gửi ảnh và nhãn chăm sóc qua Zalo", "DN House xác nhận có phù hợp nhận xử lý không", "Chỉ chốt giá và thời gian sau khi kiểm tra"]
    };
  }

  return {
    title: "Giặt quần áo tại DN House",
    facts: ["Giặt phơi từ 3kg: 7K/kg", "Giặt sấy từ 3kg: 9K/kg; dưới 3kg: 35K/lần", "Freeship trong bán kính 3km sau khi xác nhận"]
  };
}

export function getRelatedGuides(current: Guide, allGuides: Guide[]) {
  const currentTags = new Set(getGuideAdvice(current.slug)?.tags ?? []);
  return allGuides
    .filter((candidate) => candidate.slug !== current.slug)
    .map((candidate) => {
      const candidateTags = getGuideAdvice(candidate.slug)?.tags ?? [];
      const sharedTags = candidateTags.filter((tag) => currentTags.has(tag)).length;
      const sameCategory = candidate.category === current.category ? 1 : 0;
      const sameService = candidate.serviceSlug === current.serviceSlug ? 0.25 : 0;
      return { candidate, score: sharedTags * 3 + sameCategory + sameService };
    })
    .sort((a, b) => b.score - a.score || a.candidate.title.localeCompare(b.candidate.title, "vi"))
    .slice(0, 3)
    .map(({ candidate }) => candidate);
}

export function getMissingAdviceSlugs(guides: Guide[]) {
  return guides.filter((guide) => !advice[guide.slug]).map((guide) => guide.slug);
}
