export const SYSTEM = 'Bạn là biên tập viên nghiên cứu và viết nội dung cho thư viện DN House theo editorial charter. Không bịa nguồn, số liệu, quy trình nội bộ hoặc trải nghiệm. Ưu tiên an toàn hóa chất, giới hạn xử lý và tiếng Việt tự nhiên, cụ thể, hữu ích.';

export function researchPrompt(item, charter) {
  return `Đọc editorial charter sau:\n\n${charter}\n\nNghiên cứu nhiệm vụ từ manifest:\n${JSON.stringify(item, null, 2)}\n\nTrả về DUY NHẤT JSON hợp lệ gồm: slug, researchSummary, readerQuestions (array), immediateActions (array), keyFacts (array object claim, nuance, sourceIds), waterTemperatureGuidance, allowedTreatments (array), forbiddenMixtures (array), materialAndColorRisks (array), stopConditions (array), recommendedStructure (array), sources (array object id,title,publisher,url,sourceType,accessedAt,supportsClaims), risksAndCaveats (array), internalLinkIdeas (array). Phân biệt kiến thức phổ quát với dữ liệu địa phương chưa được xác nhận. Chỉ đề xuất URL HTTPS có khả năng là nguồn thật, đúng hệ kiến thức. Không viết bài ở bước này và không coi URL đề xuất là đã xác minh.`;
}

export function writerPrompt(item, research, charter) {
  return `Đọc editorial charter:\n\n${charter}\n\nManifest:\n${JSON.stringify(item, null, 2)}\n\nResearch checkpoint:\n${JSON.stringify(research, null, 2)}\n\nViết bản nháp MDX hoàn chỉnh. Front matter YAML bắt buộc: title, slug, description, category, primaryEntity, searchIntent, contentType, stainType, garmentType, colorClass, material, stainAge, treatmentRisk, parentHub, canonical, sources (danh sách URL), status: draft, updatedAt: ${new Date().toISOString().slice(0, 10)}. Sau front matter có đúng một H1 giống hệt title, rồi đoạn **Câu trả lời nhanh:** 40–70 từ. Canonical phải là https://www.giatsaycantho.vn/thu-vien/${item.slug}. Tuân thủ cảnh báo an toàn và không hứa sạch 100%. Không raw HTML, không code fence bao toàn bài, không CTA dày, không nguồn giả hoặc link markdown chết. Cuối bài có CTA mềm gửi ảnh qua Zalo để kiểm tra và mục ## Nguồn tham khảo với các link đã dùng. Ghi rõ nguồn vẫn cần xác minh nếu research chưa có retrieval.`;
}
