"""Create contact sheets and final Vietnamese-titled SEO images from selected sources.

Usage:
  python scripts/prepare-seo-image-batch.py contact --source "C:\\path\\to\\downloads"
  python scripts/prepare-seo-image-batch.py render --manifest content-development/image-workflow/selected-images.json

The manifest maps one selected source image to one SEO topic.  Text is rendered
locally with Pillow, not generated by AI, so Vietnamese accents stay exact.
"""

from __future__ import annotations

import argparse
import shutil
import json
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps

ROOT = Path(__file__).resolve().parents[1]
LOGO_PATH = ROOT / "public" / "dn-house-logo.jpg"
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}
FONT_CANDIDATES = [
    Path(r"C:\Windows\Fonts\arialbd.ttf"),
    Path(r"C:\Windows\Fonts\segoeuib.ttf"),
]


def font(size: int) -> ImageFont.FreeTypeFont:
    for candidate in FONT_CANDIDATES:
        if candidate.exists():
            return ImageFont.truetype(candidate, size=size)
    raise FileNotFoundError("Không tìm thấy font bold Windows để render tiếng Việt.")


def files_in(source: Path) -> list[Path]:
    return sorted(
        (path for path in source.iterdir() if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS),
        key=lambda path: path.name.lower(),
    )


def make_contact_sheets(source: Path, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    files = files_in(source)
    if not files:
        raise SystemExit(f"Không tìm thấy ảnh trong: {source}")
    cell_w, cell_h, cols = 300, 260, 5
    rows_per_sheet = 6
    label_font = font(20)
    for start in range(0, len(files), cols * rows_per_sheet):
        group = files[start : start + cols * rows_per_sheet]
        rows = math.ceil(len(group) / cols)
        sheet = Image.new("RGB", (cols * cell_w, rows * cell_h), "#f3f6fb")
        draw = ImageDraw.Draw(sheet)
        for index, path in enumerate(group):
            with Image.open(path) as original:
                preview = ImageOps.contain(original.convert("RGB"), (cell_w - 16, cell_h - 52))
            x, y = (index % cols) * cell_w, (index // cols) * cell_h
            sheet.paste(preview, (x + (cell_w - preview.width) // 2, y + 8))
            draw.text((x + 8, y + cell_h - 36), f"{start + index + 1:03d}  {path.name[:23]}", fill="#102a43", font=label_font)
        sheet.save(output / f"contact-sheet-{start // (cols * rows_per_sheet) + 1:02d}.jpg", quality=92)


def wrapped_lines(draw: ImageDraw.ImageDraw, text: str, used_font: ImageFont.FreeTypeFont, max_width: int) -> list[str]:
    words = text.split()
    lines: list[str] = []
    line = ""
    for word in words:
        attempt = word if not line else f"{line} {word}"
        if draw.textbbox((0, 0), attempt, font=used_font)[2] <= max_width:
            line = attempt
        else:
            if line:
                lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def render(manifest_path: Path) -> None:
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    destination = ROOT / "public" / "seo-images" / "final"
    destination.mkdir(parents=True, exist_ok=True)
    for item in data["items"]:
        source = Path(item["source"])
        if not source.exists():
            raise FileNotFoundError(f"Thiếu ảnh nguồn cho {item['slug']}: {source}")
        with Image.open(source) as original:
            image = ImageOps.fit(original.convert("RGB"), (1600, 1600), method=Image.Resampling.LANCZOS)
        draw = ImageDraw.Draw(image)
        band_height = 330
        draw.rectangle((0, 0, 1600, band_height), fill="#062c68")
        headline_font = font(98)
        lines = wrapped_lines(draw, item["headline"], headline_font, 1440)
        while len(lines) > 2 and headline_font.size > 54:
            headline_font = font(headline_font.size - 6)
            lines = wrapped_lines(draw, item["headline"], headline_font, 1440)
        line_height = headline_font.size + 14
        block_height = len(lines) * line_height
        y = (band_height - block_height) // 2 - 4
        for line in lines:
            text_width = draw.textbbox((0, 0), line, font=headline_font, stroke_width=2)[2]
            x = (1600 - text_width) // 2
            draw.text((x, y), line, font=headline_font, fill="white", stroke_width=2, stroke_fill="#031a3d")
            y += line_height
        # A compact brand lockup: retain the DN mark + DN House name, omit the
        # tiny contact copy from the original square logo so it stays legible.
        with Image.open(LOGO_PATH) as full_logo:
            logo = full_logo.convert("RGB").crop((330, 420, 950, 1030))
        logo.thumbnail((172, 172), Image.Resampling.LANCZOS)
        panel_w, panel_h, margin = logo.width + 32, logo.height + 32, 40
        panel_x, panel_y = 1600 - panel_w - margin, 1600 - panel_h - margin
        draw.rounded_rectangle(
            (panel_x, panel_y, panel_x + panel_w, panel_y + panel_h),
            radius=20,
            fill="#ffffff",
            outline="#dce8f5",
            width=2,
        )
        image.paste(logo, (panel_x + 16, panel_y + 16))
        image.save(destination / f"{item['slug']}.jpg", quality=94, optimize=True)


def select_images(selection_path: Path, source: Path, output: Path) -> None:
    """Build a human-readable manifest and copy the 50 selected originals."""
    choices = json.loads(selection_path.read_text(encoding="utf-8"))["items"]
    source_files = files_in(source)
    if len(choices) != 50:
        raise ValueError(f"Cần đúng 50 lựa chọn, đang có {len(choices)}.")
    selected_dir = output.parent / "selected-originals"
    selected_dir.mkdir(parents=True, exist_ok=True)
    items = []
    seen_indexes: set[int] = set()
    for choice in choices:
        index = choice["sourceIndex"]
        if index in seen_indexes or not 1 <= index <= len(source_files):
            raise ValueError(f"sourceIndex không hợp lệ/trùng: {index}")
        seen_indexes.add(index)
        original = source_files[index - 1]
        copied = selected_dir / original.name
        shutil.copy2(original, copied)
        items.append({
            "id": choice["id"],
            "slug": choice["slug"],
            "headline": choice["headline"],
            "source": str(copied.resolve()),
            "selectionReason": choice["selectionReason"],
        })
    output.write_text(json.dumps({"items": items}, ensure_ascii=False, indent=2), encoding="utf-8")


parser = argparse.ArgumentParser()
sub = parser.add_subparsers(dest="command", required=True)
contact = sub.add_parser("contact")
contact.add_argument("--source", type=Path, required=True)
contact.add_argument("--output", type=Path, default=ROOT / "content-development" / "image-workflow" / "contact-sheets")
render_cmd = sub.add_parser("render")
render_cmd.add_argument("--manifest", type=Path, required=True)
select_cmd = sub.add_parser("select")
select_cmd.add_argument("--selection", type=Path, required=True)
select_cmd.add_argument("--source", type=Path, required=True)
select_cmd.add_argument("--output", type=Path, default=ROOT / "content-development" / "image-workflow" / "selected-images.json")
args = parser.parse_args()

if args.command == "contact":
    make_contact_sheets(args.source, args.output)
elif args.command == "render":
    render(args.manifest)
else:
    select_images(args.selection, args.source, args.output)
